default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  timeout: 5000
  reconnect: true

development:
  <<: *default
  database: comics_development

test:
  <<: *default
  database: comics_test

production:
  primary:
    <<: *default
    database: comics_production
  cache:
    <<: *default
    database: comics_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: comics_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: comics_production_cable
    migrations_paths: db/cable_migrate